---
- name: Download
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_{{ lazydocker_version }}_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: true
    include:
      - lazydocker
