---
- name: Download
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lazygit"
    state: directory
    mode: "0755"

- name: Create empty config file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lazygit/config.yml"
    state: touch
    mode: "0644"
    access_time: preserve
    modification_time: preserve
