---
- name: Copy dconf settings
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/dconf/dconf-settings.ini"
    src: "dconf-settings.ini"
    mode: '0755'
  register: dconf

- name: Update dconf
  ansible.builtin.shell: dconf load / < {{ ansible_user_dir }}/.config/dconf/dconf-settings.ini
  when: dconf.changed

- name: Make fonts directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.fonts"
    state: directory
    mode: '0755'

- name: Download Nerdfonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/UbuntuMono.tar.xz
    dest: /tmp/UbuntuMono.tar.xz
    mode: '0755'

- name: Unarchive Nerdfonts
  ansible.builtin.unarchive:
    src: /tmp/UbuntuMono.tar.xz
    dest: "{{ ansible_user_dir }}/.fonts/"
