---
- name: Install
  ansible.builtin.package:
    name:
      - zsh
    state: latest
  become: yes

- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes

- name: Set public
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.zsh_public"
    src: ".zsh_public.j2"

- name: Set private
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.zsh_private"
    src: ".zsh_private.j2"
  no_log: true

- name: Set zprofile
  ansible.builtin.lineinfile:
    insertafter: EOF
    line: |
      if [ -d /etc/profile.d ]; then
        for i in /etc/profile.d/*.sh; do
          if [ -r $i ]; then
            . $i
          fi
        done
        unset i
      fi
    state: present