---
- name: Install
  become: true
  ansible.builtin.apt:
    deb: https://github.com/flameshot-org/flameshot/releases/download/v{{ flameshot_version }}/flameshot-{{ flameshot_version }}-1.debian-12.amd64.deb
