---
- name: Install
  ansible.builtin.package:
    name:
      - git
  become: true

- name: Set diff.colorMoved
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra

- name: Set fetch.prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true

- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: Set rebase.autoStash
  community.general.git_config:
    name: rebase.autoStash
    scope: global
    value: true

- name: Set aliases
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - name: alias.co
      value: checkout
    - name: alias.br
      value: branch
    - name: alias.commit
      value: commit
    - name: alias.st
      value: status

# Not sure what is the best git-credential-maanger or caching the credentials for 1h...
- name: Set credential timeout
  community.general.git_config:
    name: credential.helper
    scope: global
    value: "cache --timeout=3600"
    add_mode: add

- name: Set credential helper manager
  community.general.git_config:
    name: credential.helper
    scope: global
    value: /usr/local/bin/git-credential-manager
    add_mode: add

- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Install git credential manager
  become: true
  ansible.builtin.apt:
    deb: "{{ git_cred_manager_uri }}"
