---
- name: Check if bottom is installed
  command: dpkg-query -W bottom
  register: bottom_check_deb
  failed_when: bottom_check_deb.rc > 1
  changed_when: bottom_check_deb.rc == 1

- name: Download
  get_url:
    url=https://github.com/ClementTsang/bottom/releases/download/{{ bottom_version }}/bottom_{{ bottom_version }}_amd64.deb
    dest=/home/{{ ansible_env.USER }}/Downloads/bottom_{{ bottom_version }}_amd64.deb
  when: bottom_check_deb.rc == 1
  
- name: Install
  apt: 
    deb=/home/{{ ansible_env.USER }}/Downloads/bottom_{{ bottom_version }}_amd64.deb
  become: yes
  when: bottom_check_deb.rc == 1
