---
- name: Clone
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ oh_my_tmux_config_dir }}"
    repo: https://github.com/gpakosz/.tmux.git
    single_branch: true
    update: true
    version: master
  register: clone

- name: Link .tmux.conf
  ansible.builtin.file:
    src: "{{ oh_my_tmux_config_dir }}/.tmux.conf"
    dest: "{{ oh_my_tmux_config_dir }}/tmux.conf"
    state: link

- name: Copy .tmux.conf.local
  ansible.builtin.template:
    dest: "{{ oh_my_tmux_config_dir }}/tmux.conf.local"
    src: "tmux.conf.local.j2"
    mode: "0644"

- name: Clone TPM
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ oh_my_tmux_config_dir }}/plugins/tpm"
    repo: https://github.com/tmux-plugins/tpm
    single_branch: true
    update: true
    version: master
  register: clone
