---
- name: Create extensions temporary directory
  file:
    path: /tmp/vbox-extpacks
    state: directory
    mode: '0777'

- name: download extpack
  get_url:
    dest: /tmp/vbox-extpacks/
    url: "{{ item }}"
  with_items: "{{ virtualbox_extpack_urls }}"

- name: List downloaded extpacks
  find:
    paths: /tmp/vbox-extpacks
  register: extpacks

  # - debug:
  #     var: item.path
  #   with_items: "{{ extpacks.files }}"

- name: check installed extpacks
  shell: |
      set -o pipefail
      vboxmanage list extpacks | grep Usable
  args:
    executable: /bin/bash
  register: extpack_installed
  ignore_errors: yes
  changed_when: False

- debug: msg={{ extpack_installed }}

- name: install extpacks
  command: 
    cmd: vboxmanage extpack install --replace "{{ item.path }}" --accept-license=29cf8410e2514ea4393f63f5e955b8311787873679fc23ae9a897fb70ef3f84a
    stdin: "y"
  with_items: "{{ extpacks.files }}"
  when: "'false' not in extpack_installed.stdout"
  become: yes