---
- name: Check if pyenv is already installed
  ansible.builtin.command: 'which pyenv'
  register: pyenv_installed
  failed_when: pyenv_installed.rc > 1
  changed_when: pyenv_installed.rc == 1

- name: Download, Install, Cleanup
  block:
    - name: Download
      ansible.builtin.get_url: 
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv-installer
        mode: 0700

    - name: Install
      ansible.builtin.command: |
        bash /tmp/pyenv-installer

    - name: Remove script
      ansible.builtin.file:
        path: /tmp/pyenv-installer
        state: absent

  when: pyenv_installed.rc != 0
