---
- name: Install
  become: true
  ansible.builtin.apt:
    deb: https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_version }}/fastfetch-linux-amd64.deb

- name: Create config directory
  ansible.builtin.file:
    name: ~/.config/fastfetch
    state: directory
    mode: "0755"

- name: Copy configuration
  ansible.builtin.copy:
    src: fastfetch.jsonc
    dest: ~/.config/fastfetch/config.jsonc
    mode: "0644"
