---
# TODO make it idempotent
- name: Download fastfetch
  ansible.builtin.get_url:
    url: https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_version }}/fastfetch-linux-amd64.deb
    dest: /tmp/fastfetch.deb
    mode: '0755'

- name: Create config directory
  ansible.builtin.file:
    name: ~/.config/fastfetch
    state: directory
    mode: "0755"

- name: Copy configuration
  ansible.builtin.copy:
    src: fastfetch.jsonc
    dest: config.jsonc
    mode: "0644"

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/fastfetch.deb
    state: absent
