- name: Download and Install
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/eza-community/eza/releases/download/v{{ eza_version }}/eza_x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: true
