---
- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: "{{ anaconda_installer_uri }}"
        dest: /tmp/install-miniconda.sh
        checksum: "sha256:{{ anaconda_installer_sha256 }}"
        mode: 0550
    - name: Create conda folder
      become: True
      file:
        path: "{{ anaconda_home_dir }}"
        state: directory
        mode: 755
        recurse: yes
    - name: Run the installer
      become: True
      shell: /tmp/install-miniconda.sh -b -u -p {{ anaconda_home_dir }}
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh

    # Set miniconda environment variables
    - name: Make sure /etc/profile.d exists
      become: true
      ansible.builtin.file:
        path: /etc/profile.d
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'

    - name: Export environment variables
      become: true
      ansible.builtin.template:
        src: miniconda.sh.j2
        dest: /etc/profile.d/miniconda.sh
        owner: root
        group: root
        mode: 'u=rw,go=r'

    - name: conda - read permission for all
      become: True
      file:
        path: "{{ anaconda_home_dir }}"
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: "{{ anaconda_home_dir }}/bin"
        mode: +x
        recurse: yes