---
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - gir1.2-gtop-2.0
      - gir1.2-clutter-1.0
      - gnome-tweaks
      - gnome-sushi # Gives you previews in the file manager when pressing space

- name: Install gnome extensions
  ansible.builtin.import_tasks: install_gnome_extensions.yml

- name: Set gnome hotkeys
  ansible.builtin.import_tasks: set_gnome_hotkeys.yml

- name: Set gnome settings
  ansible.builtin.import_tasks: set_gnome_settings.yml

- name: Remove desktop entry
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/applications/btop.desktop # Remove Btop entry for one that runs in alacritty
    - /usr/share/applications/org.flameshot.Flameshot.desktop # App doesn't do anything when started from the app grid
    - /usr/share/applications/display-im6.q16.desktop # Remove the ImageMagick icon
    - /usr/share/applications/org.gnome.SystemMonitor.desktop # Replacing this with btop
    # We added our own meant for Alacritty
    - /usr/local/share/applications/nvim.desktop
    - /usr/local/share/applications/vim.desktop

# TODO maybe add custom app-folder structure later
