[env]
TERM = "xterm-256color"

[terminal.shell]
program = "tmux"
args = [
  "new-session",
  "-A",
  "-D",
  "-s",
  "main"
]

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
