---
- name: Download and install neovim
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux-x86_64.tar.gz
    dest: /usr/local/
    remote_src: true
    mode: '0755'

- name: Download and install tree-siter # noqa: command-instead-of-module
  become: true
  ansible.builtin.shell:
    cmd: |
      curl -OL https://github.com/tree-sitter/tree-sitter/releases/download/v{{ neovim_tree_sitter_version }}/tree-sitter-linux-x64.gz
      gunzip tree-sitter-linux-x64.gz
      chmod +x tree-sitter-linux-x64
      mv tree-sitter-linux-x64 /usr/local/bin/tree-sitter
    creates: /usr/local/bin/tree-sitter

- name: Install luarocks
  become: true
  ansible.builtin.apt:
    name: luarocks
    install_recommends: false

- name: Clone lazyvim
  ansible.builtin.git:
    clone: true
    depth: 1
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    repo: https://github.com/LazyVim/starter
    single_branch: true
    update: true
    version: main

- name: Create plugin-after directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/plugin/after"
    state: directory
    mode: "0755"

- name: Make everything match the terminal transparency
  ansible.builtin.copy:
    src: transparency.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/plugin/after/"
    mode: "0644"

- name: Turn off animated scrolling
  ansible.builtin.copy:
    src: snacks-animated-scrolling-off.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/plugins/"
    mode: "0644"

- name: Turn off relative line numbers
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/nvim/lua/config/options.lua"
    search_string: vim.opt.relativenumber = false
    line: vim.opt.relativenumber = false

- name: Ensure editor.neo-tree is used by default
  ansible.builtin.copy:
    src: lazyvim.json
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    mode: "0644"

- name: Create desktop launcher file
  ansible.builtin.template:
    src: neovim.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/Neovim.desktop"
    mode: "0644"
