---
- name: Add neovim ppa
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  become: yes

- name: Install neovim from ppa
  apt:
    name: neovim
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: Copy init.lua
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
    src: "init.lua"

- name: Copy modules
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua"
    src: "lua/"
