---
- name: Create fonts directory
  ansible.builtin.file:
    path: ~/.local/share/fonts
    state: directory
    mode: "0755"

- name: Install nerd-fonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip
    dest: ~/.local/share/fonts
    remote_src: true
    include:
      - "*.ttf"

- name: Install iA-Fonts
  ansible.builtin.unarchive:
    src: https://github.com/iaolo/iA-Fonts/archive/refs/heads/master.zip
    dest: ~/.local/share/fonts
    remote_src: true
    include:
      - "iA-Fonts-master/iA\ Writer\ Mono/Static/iAWriterMonoS-*.ttf"
